proteins = float(input("Введите массу белков (г): "))
fats = float(input("Введите массу жиров (г): "))
carbohydrates = float(input("Введите массу углеводов (г): "))
calories = (proteins * 4) + (fats * 9) + (carbohydrates * 4)
print(f"Калорийность продукта: {calories} ккал")